"""Distributional comparison of our Python baselines with the authors' MATLAB runs.

MATLAB (twister) random streams cannot be reproduced in NumPy, so validation is
distributional: for every (method, instance) we compare our baseline-validation
runs (disjoint seeds) with the authors' 30 published runs
(third_party/mphbs_reference/results/*_external_*/task_results.csv) using a
two-sided Mann-Whitney U test (Holm-corrected over all comparisons of a
domain), the ratio of medians, and the agreement of per-instance method
rankings (Kendall tau between our and their mean-based ranks).
Writes experiments/baseline_validation.md and results/validation/baseline_validation.csv.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from lakaie.analysis.stats import holm, load_campaign  # noqa: E402

REF = ROOT / "third_party" / "mphbs_reference" / "results"
ALIAS = {"B-C1": "MPHBS", "A-C1": "MPHBS", "MPHB": "MPHB", "HBA": "HBA", "MPA": "MPA"}


def authors(domain):
    if domain == "CEC2022":
        d = pd.read_csv(REF / "CEC2022_external_BC1_common_seeds" / "task_results.csv")
        d = d.rename(columns={"FunctionID": "instance", "Error": "value"})
    else:
        d = pd.read_csv(REF / "FIR_external_AC1_common_seeds" / "task_results.csv")
        d = d.rename(columns={"CaseID": "instance", "BestFit": "value"})
    d = d[d.Alias.isin(ALIAS)].copy()
    d["method"] = d.Alias.map(ALIAS)
    return d[["method", "instance", "value", "RunIdx"]]


def compare(domain):
    ours = load_campaign(ROOT / "results" / "raw", "baseline_validation", domain)
    if ours.empty:
        return None
    ours = ours[ours.status == "ok"]
    ref = authors(domain)
    rows = []
    for (m, inst), g in ours.groupby(["method", "instance"]):
        a = g.best_fitness.values.astype(float)
        b = ref[(ref.method == m) & (ref.instance == inst)].value.values.astype(float)
        if b.size == 0:
            continue
        p = stats.mannwhitneyu(a, b, alternative="two-sided").pvalue if not np.allclose(np.r_[a, b], a[0]) else 1.0
        rows.append({"domain": domain, "method": m, "instance": inst, "n_ours": a.size, "n_authors": b.size,
                     "mean_ours": a.mean(), "mean_authors": b.mean(),
                     "median_ours": np.median(a), "median_authors": np.median(b),
                     "median_ratio": np.median(a) / np.median(b) if np.median(b) != 0 else np.nan,
                     "mwu_p": p})
    T = pd.DataFrame(rows)
    T["mwu_p_holm"] = holm(T["mwu_p"].values)
    # ranking agreement per instance
    taus = []
    for inst, g in T.groupby("instance"):
        if len(g) >= 3:
            taus.append(stats.kendalltau(g.mean_ours.rank(), g.mean_authors.rank()).statistic)
    return T, float(np.nanmean(taus)) if taus else np.nan


def fmt(x):
    return f"{x:.3e}" if isinstance(x, (float, np.floating)) and np.isfinite(x) else str(x)


def main():
    out_csv = ROOT / "results" / "validation" / "baseline_validation.csv"
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    parts, lines = [], []
    lines.append("# Baseline validation: Python port vs authors' MATLAB results\n")
    lines.append("Generated by `scripts/compare_baseline_validation.py`. Our runs: campaign "
                 "`baseline_validation` (seeds disjoint from the main experiment). Authors' runs: "
                 "30 published runs per instance from the MPHBS reproducibility package "
                 "(`third_party/mphbs_reference/results/*_external_*`), MPHBS = B-C1 (CEC2022) / A-C1 (FIR).\n")
    lines.append("MATLAB random streams cannot be reproduced in NumPy; agreement is assessed "
                 "distributionally (two-sided Mann-Whitney U, Holm-corrected within domain). "
                 "A non-significant test does not prove equivalence; with 10 vs 30 runs the test "
                 "has limited power, so the median ratio and the rank agreement are reported too.\n")
    for dom in ["CEC2022", "FIR"]:
        res = compare(dom)
        if res is None:
            lines.append(f"\n## {dom}\n\nNo runs found.\n")
            continue
        T, tau = res
        parts.append(T)
        nsig = int((T.mwu_p_holm < 0.05).sum())
        lines.append(f"\n## {dom}\n")
        lines.append(f"* comparisons: {len(T)}; significantly different after Holm: **{nsig}**")
        lines.append(f"* mean Kendall tau between our and the authors' per-instance method rankings: **{tau:.3f}**")
        lines.append(f"* median ratio ours/authors: median {np.nanmedian(T.median_ratio):.3f}, "
                     f"range [{np.nanmin(T.median_ratio):.3g}, {np.nanmax(T.median_ratio):.3g}]\n")
        lines.append("| method | inst | median ours | median authors | ratio | MWU p (Holm) |")
        lines.append("|---|---|---|---|---|---|")
        for _, r in T.sort_values(["method", "instance"]).iterrows():
            flag = " **" if r.mwu_p_holm < 0.05 else ""
            lines.append(f"| {r.method} | {r.instance} | {fmt(r.median_ours)} | {fmt(r.median_authors)} | "
                         f"{r.median_ratio:.3g} | {r.mwu_p_holm:.3g}{flag} |")
    if parts:
        pd.concat(parts).to_csv(out_csv, index=False)
    (ROOT / "experiments" / "baseline_validation_results.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines[:40]))


if __name__ == "__main__":
    main()
